-- QUESTIONS:

-- Q-6: INSERT THE FOLLOWING TWO ROWS IN THE 'CUSTOMERS' TABLE.
-- (495,'DIECAST COLLECTABLES','FRANCO','VALARIE','BOSTON','MA','51003','USA','1188',85100),
-- (496,'KELLY\'S GIFT SHOP','SNOWDEN','TONY','AUCKLAND  ','NULL','NULL','NEW ZEALAND','1612',110000)
INSERT INTO CUSTOMERS
VALUES(495,'DIECAST COLLECTABLES','FRANCO','VALARIE','BOSTON','MA','51003','USA','1188',85100),
(496,'KELLY\'S GIFT SHOP','SNOWDEN','TONY','AUCKLAND ','NULL','NULL','NEW ZEALAND','1612',110000);

-- Q-7: IN THE "EMPLOYEES" TABLE THERE ARE SOME ENTRIES WHERE 'SR' IS WRITTEN INSTEAD OF 'SALES REP' WHERE OFFICE CODE IS EQUAL TO 4.
-- UPDATE THE 'EMPLOYEES' TABLE BY INSERTING A JOB TITLE AS 'SALES REP' WHERE OFFICE CODE IS EQUAL TO 4.
UPDATE EMPLOYEES SET JOBTITLE = 'SALES REP' WHERE OFFICECODE = 4;

-- Q-8: THERE IS NO PRODUCT UNDER CATEGORY OF BOAT. HENCE, DELETE THE BOAT ENTRY FROM PRODUCTLINES TABLE.
DELETE FROM PRODUCTLINES WHERE PRODUCTLINE = 'BOATS';

-- Q-9: CONVERT THE 'QUANTITYORDERED' COLUMN'S DATA TYPE INTO INT FROM VARCHAR.
ALTER TABLE ORDERDETAILS MODIFY COLUMN QUANTITYORDERED INT;

-- Q-10: PRINT THE EMPLOYEES WITH THE JOB TITLE “SALES REP”. 
-- WHAT IS THE FIRST NAME OF THE EMPLOYEE THAT APPEARS ON THE TOP AFTER APPLYING THIS QUERY?
SELECT FIRSTNAME, JOBTITLE FROM EMPLOYEES WHERE JOBTITLE = 'SALES REP';

-- INSERT THE FOLLOWING ENTRY INTO THE EMPLOYEE TABLE.
INSERT INTO EMPLOYEES 
VALUES(1102, 'BONDUR', 'GERARD', 'X5408', 'GBONDUR@CLASSICMODELCARS.COM', 4, '1056', 'SALE MANAGER(EMEA)');

-- Q-10: FIND THE TOTAL NUMBER OF EMPLOYEES FROM THE 'EMPLOYEES’ TABLE AND ALIAS IT AS "TOTAL_EMPLOYEES".
SELECT COUNT(*) AS TOTAL_EMPLOYEES FROM EMPLOYEES;

-- Q-10: HOW MANY CUSTOMERS BELONGS TO AUSTRALIA? ALSO ALIAS IT AS "AUSTRALIA_CUSTOMERS".
SELECT COUNT(*) AS AUSTRALIA_CUSTOMERS FROM CUSTOMERS WHERE COUNTRY = 'AUSTRALIA';

-- Q-11: PRINT THE QUANTITY IN STOCK FOR "RED START DIECAST" PRODUCT VENDORS WITH PRODUCT LINE IS "VINTAGE CARS" FROM THE TABLE "PRODUCTS".
SELECT QUANTITYINSTOCK, PRODUCTVENDOR, PRODUCTLINE FROM PRODUCTS WHERE PRODUCTVENDOR = 'RED START DIECAST' AND PRODUCTLINE = 'VINTAGE CARS';

-- Q-11: COUNT THE TOTAL NUMBER OF ORDERS THAT HAS NOT BEEN SHIPPED YET IN THE "ORDERS" TABLE. 
SELECT COUNT(*) FROM ORDERS WHERE STATUS != 'SHIPPED';

-- Q-12: COUNT THE ENTRIES IN "ORDERDETAILS" TABLE WITH "PRODUCTCODE" STARTS WITH S18 AND "PRICEEACH" GREATER THAN 150.
SELECT COUNT(*) PRODUCTCODE FROM ORDERDETAILS WHERE PRODUCTCODE LIKE 'S18%' AND PRICEEACH > 150;

-- Q- 13: WHAT ARE THE TOP THREE COUNTRIES WHICH HAVE THE MAXIMUM NUMBER OF CUSTOMERS?
SELECT COUNTRY,COUNT(CUSTOMERNAME) AS COUNT FROM CUSTOMERS GROUP BY COUNTRY ORDER BY COUNT DESC LIMIT 3;

-- Q-14: WHAT IS THE AVERAGE CREDIT LIMIT FOR SINGAPORE FROM "CUSTOMERS" TABLE?
SELECT COUNTRY, AVG(CREDITLIMIT) AS CREDIT_LIMIT FROM CUSTOMERS WHERE COUNTRY= 'SINGAPORE';

-- Q-15: WHAT IS THE TOTAL AMOUNT TO BE PAID BY THE CUSTOMER NAMED AS “EURO+ SHOPPING CHANNEL”?
-- YOU NEED TO USE THE “CUSTOMERS” AND “PAYMENTS” TABLES TO ANSWER THIS QUESTION.
SELECT CUSTOMERNAME,SUM(AMOUNT) AS TOTAL_AMOUNT FROM CUSTOMERS C
INNER JOIN PAYMENTS P
ON C.CUSTOMERNUMBER = P.CUSTOMERNUMBER 
WHERE CUSTOMERNAME= 'EURO+ SHOPPING CHANNEL'
GROUP BY CUSTOMERNAME;

-- Q-16: WHICH MONTH HAS RECIEVED THE MAXIMUM AGGRAGATED PAYMENTS FROM THE CUSTOMERS? 
-- Q-16: WHAT IS THE AGGREGATED VALUE OF THE PAYMENT RECIEVED FROM THAT MONTH?
SELECT MONTH(PAYMENTDATE) AS MONTH,SUM(AMOUNT) AS AMOUNT FROM PAYMENTS
GROUP BY MONTH
ORDER BY AMOUNT DESC LIMIT 1;

-- Q-17: WHAT IS THE SHIPPED DATE OF THE MAXIMUM QUANTITY ORDERED FOR "1968 FORD MUSTANG" PRODUCT NAME?
SELECT * FROM PRODUCTS P 
INNER JOIN ORDERS O 
WHERE PRODUCTNAME = '1968 FORD MUSTANG';

-- Q-18: INNER JOIN:  WHAT IS THE AVERAGE VALUE OF CREDIT LIMIT CORRESPONDS TO THE CUSTOMERS WHICH HAVE BEEN CONTACTED BY THE EMPLOYEES WITH THEIR OFFICE LOCATED IN “TOKYO” CITY? 
SELECT AVG(CREDITLIMIT) FROM CUSTOMERS C
INNER JOIN EMPLOYEES E 
ON C.SALESREPEMPLOYEENUMBER = E.EMPLOYEENUMBER
WHERE OFFICECODE = (SELECT OFFICECODE FROM OFFICES WHERE OFFICE_CITY = 'TOKYO');

-- Q-19: OUTER JOIN: WHAT IS THE NAME OF THE CUSTOMER WHICH HAS PAID THE LOWEST AMOUNT TO THE COMPANY. 
SELECT SUM(AMOUNT) AS AMOUNT,P.CUSTOMERNUMBER,CUSTOMERNAME FROM PAYMENTS P
LEFT JOIN CUSTOMERS C
ON C.CUSTOMERNUMBER = P.CUSTOMERNUMBER
GROUP BY P.CUSTOMERNUMBER
ORDER BY SUM(AMOUNT) LIMIT 1;

-- Q-20: OUTER JOIN: WHAT IS THE CITY OF THE EMPLOYEE WHOSE JOB TITLE IS "VP MARKETING" ? 
SELECT OFFICE_CITY FROM EMPLOYEES E 
LEFT JOIN OFFICES O
ON E.OFFICECODE = O.OFFICECODE
WHERE JOBTITLE = 'VP MARKETING';

-- Q-21: WHAT IS THE NAME OF THE CUSTOMER WHO BELONGS TO ‘USA’ AND HAS THE MAXIMUM CREDITLIMIT AMONG THE CUSTOMERS IN FRANCE?
SELECT CUSTOMERNAME FROM CUSTOMERS
WHERE CREDITLIMIT = (SELECT MAX(CREDITLIMIT) FROM CUSTOMERS WHERE COUNTRY = 'USA' GROUP BY COUNTRY);

-- Q-22: WHAT WILL BE THE REMAINING STOCK OF THE PRODUCT CODE THAT EQUALS ‘S18_1589’ IF IT IS SENT TO ALL THE CUSTOMERS WHO HAVE DEMANDED IT?
SELECT QUANTITYINSTOCK FROM PRODUCTS WHERE PRODUCTCODE = 'S18_1589';
SELECT SUM(QUANTITYORDERED) FROM ORDERDETAILS WHERE PRODUCTCODE="S18_1589";

-- Q-23: WHAT IS THE AVERAGE AMOUNT PAID BY THE CUSTOMER 'MINI GIFTS DISTRIBUTORS LTD.'?
SELECT AVG(AMOUNT),CUSTOMERNAME FROM CUSTOMERS C 
LEFT JOIN PAYMENTS P
ON C.CUSTOMERNUMBER = P.CUSTOMERNUMBER
WHERE CUSTOMERNAME = 'MINI GIFTS DISTRIBUTORS LTD.'
GROUP BY P.CUSTOMERNUMBER;
